[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[rpc_endpoints]
anvil = "${RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
[profile.private_keys]
anvil = { key = "${PRIVATE_KEY}" }
sepolia = { key = "${SEPOLIA_PRIVATE_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
